[workspace]
resolver = "3"
members = ["crates/noted-db", "crates/noted-crdt", "crates/noted-server", "crates/noted-index"]

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
tokio = { version = "1.53", features = ["full"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "postgres", "uuid", "chrono", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
thiserror = "2"
tracing = "0.1"
