//! Share links: public, tokenised access to one page.
//!
//! # The blast radius is the whole point
//!
//! A share token is a credential held by someone with NO account, so what it
//! reaches has to be exactly what the sharer intended and nothing adjacent. It
//! grants one page — plus that page's descendants, and only when the link says
//! so. It never grants the workspace, never grants search, and never grants a
//! sibling.
//!
//! [`shared_page_ids`] is the single answer to "what does this token reach",
//! and every route serving a token goes through it rather than deciding for
//! itself.
use chrono::{DateTime, Utc};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, sqlx::FromRow)]
pub struct ShareLink {
    pub page_id: Uuid,
    pub include_descendants: bool,
    pub expires_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

/// Create a link. `token_hash` is the hash of the token; the token itself is
/// generated by the caller and never stored.
pub async fn create(
    pool: &sqlx::PgPool,
    token_hash: &str,
    page_id: Uuid,
    created_by: Uuid,
    include_descendants: bool,
    expires_at: Option<DateTime<Utc>>,
) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT INTO share_links
             (token_hash, page_id, created_by, include_descendants, expires_at)
         VALUES ($1, $2, $3, $4, $5)",
    )
    .bind(token_hash)
    .bind(page_id)
    .bind(created_by)
    .bind(include_descendants)
    .bind(expires_at)
    .execute(pool)
    .await?;
    Ok(())
}

/// Resolve a token to its link, if the link is live.
///
/// EXPIRY IS PART OF THE QUERY (`expires_at IS NULL OR expires_at > now()`).
/// A background sweeper that fell behind would leave expired links serving
/// content, and nothing would report it.
///
/// The page must also still be live: archiving a shared page revokes its links
/// implicitly, which is what a user deleting a page expects even though they
/// were not thinking about the link at the time.
pub async fn resolve(
    pool: &sqlx::PgPool,
    token_hash: &str,
) -> Result<Option<ShareLink>, sqlx::Error> {
    sqlx::query_as::<_, ShareLink>(
        "SELECT s.page_id, s.include_descendants, s.expires_at, s.created_at
         FROM share_links s
         JOIN pages p ON p.id = s.page_id
         WHERE s.token_hash = $1
           AND (s.expires_at IS NULL OR s.expires_at > now())
           AND p.archived_at IS NULL",
    )
    .bind(token_hash)
    .fetch_optional(pool)
    .await
}

/// Exactly which pages a token reaches.
///
/// One page, or that page and its descendants — never more. The recursion walks
/// DOWN from the shared page only, so a link can never reach a parent or a
/// sibling however deep the tree is.
///
/// Archived descendants are excluded: a page the owner deleted must not stay
/// readable to a stranger because a link to its parent predates the deletion.
pub async fn shared_page_ids(
    pool: &sqlx::PgPool,
    link: &ShareLink,
) -> Result<Vec<Uuid>, sqlx::Error> {
    if !link.include_descendants {
        return Ok(vec![link.page_id]);
    }

    sqlx::query_scalar(
        "WITH RECURSIVE shared(id) AS (
             SELECT p.id FROM pages p WHERE p.id = $1 AND p.archived_at IS NULL
           UNION ALL
             SELECT c.id
             FROM shared s
             JOIN pages c ON c.parent_id = s.id
             WHERE c.archived_at IS NULL
         )
         SELECT id FROM shared",
    )
    .bind(link.page_id)
    .fetch_all(pool)
    .await
}

/// Revoke one link. Idempotent.
pub async fn revoke(pool: &sqlx::PgPool, token_hash: &str) -> Result<bool, sqlx::Error> {
    let n = sqlx::query("DELETE FROM share_links WHERE token_hash = $1")
        .bind(token_hash)
        .execute(pool)
        .await?
        .rows_affected();
    Ok(n > 0)
}

/// Every live link on a page — what the share dialog lists.
///
/// Deliberately does NOT return `token_hash`: a hash is not a token, but
/// handing one to a client is still handing out a credential-shaped secret with
/// no use case behind it.
pub async fn for_page(pool: &sqlx::PgPool, page_id: Uuid) -> Result<Vec<ShareLink>, sqlx::Error> {
    sqlx::query_as::<_, ShareLink>(
        "SELECT page_id, include_descendants, expires_at, created_at
         FROM share_links
         WHERE page_id = $1 AND (expires_at IS NULL OR expires_at > now())
         ORDER BY created_at",
    )
    .bind(page_id)
    .fetch_all(pool)
    .await
}
